### PR TITLE
rewind and close file to write content to disk before mv file

### LINKED ISSUE #2: bundle.gradle becomes empty file after update version code
After run increment_version_code in fastlane file, the app build.gradle file becomes empty in centos.

### PR DESCRIPTION
**Pull request by haibinyu**
fix #2

### CODE REVIEW

**Comment by haibinyu** [comment]
any progress？

**Comment by Jems22** [comment]
Hello @haibinyu, and sorry for the (long) delay.
I check and test your PL rigth now, but it seems to be nice !

**Comment by Jems22** [comment]
@haibinyu Thanks for your help in your PL. 
I've merged it on the master branch, and published the updated version (0.3.1) on RubyGems.
Can you please tell me if it's ok for you (for the both issues #2 & #3) ?

**Comment by haibinyu** [comment]
@Jems22 thanks for the merge.

**Pull request merged**
